# Generated by Django 5.1.3 on 2025-01-15 09:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Дані не визначені', max_length=100, verbose_name='Назва грузу')),
                ('weight', models.DecimalField(decimal_places=2, default=0.1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1, 'Вага має бути більше 0.')], verbose_name='Вага')),
                ('customer', models.CharField(default='Невідомий замовник', max_length=100, verbose_name='Замовник')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Додаткова інформація')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Дані не визначені', max_length=50, validators=[django.core.validators.RegexValidator(message="Ім'я має містити лише літери.", regex="^[A-Za-zА-Яа-я'\\s]+$")], verbose_name="Ім'я")),
                ('last_name', models.CharField(default='Дані не визначені', max_length=50, validators=[django.core.validators.RegexValidator(message='Прізвище має містити лише літери.', regex="^[A-Za-zА-Яа-я'\\s]+$")], verbose_name='Прізвище')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='По батькові')),
                ('phone_number', models.CharField(default='0000000000', max_length=15, validators=[django.core.validators.RegexValidator(message='Введіть коректний номер телефону.', regex='^\\+?\\d{10,15}$')], verbose_name='Номер телефону')),
                ('address', models.TextField(default='Дані не визначені', verbose_name='Адреса проживання')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Дія')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час виконання')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('method', models.CharField(choices=[('cash', 'Готівка'), ('card', 'На карту')], max_length=10, verbose_name='Спосіб оплати')),
                ('status', models.BooleanField(default=False, verbose_name='Статус оплати')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.cargo', verbose_name='Замовлення')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_address', models.TextField(default='Невідома адреса', verbose_name='Адреса відправки')),
                ('sending_datetime', models.DateTimeField(verbose_name='Дата і час відправки')),
                ('delivery_address', models.TextField(default='Невідома адреса', verbose_name='Адреса доставки')),
                ('delivery_datetime', models.DateTimeField(verbose_name='Дата і час доставки')),
                ('operator_contact', models.TextField(blank=True, null=True, verbose_name='Контакти оператора')),
                ('cargo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='logistics.cargo', verbose_name='Груз')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Дані не визначені', max_length=50, verbose_name='Марка')),
                ('model', models.CharField(default='Дані не визначені', max_length=50, verbose_name='Модель')),
                ('license_plate', models.CharField(default='Невідомий номер', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Номер машини має містити лише літери, цифри та дефіс.', regex='^[A-Za-z0-9\\-]+$')], verbose_name='Номер машини')),
                ('vin_code', models.CharField(default='Невідомий VIN', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Введіть коректний VIN код.', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='VIN код')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.driver', verbose_name='Водій')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle', verbose_name='Машина для доставки'),
        ),
        migrations.CreateModel(
            name='VehicleGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Довгота')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час фіксації')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.vehicle', verbose_name='Машина')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Опис обслуговування')),
                ('date', models.DateField(verbose_name='Дата обслуговування')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вартість обслуговування')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.vehicle', verbose_name='Машина')),
            ],
        ),
    ]
